/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Entry = IDL.Record({
  'paymentConfirmed' : IDL.Bool,
  'participantName' : IDL.Text,
  'activeTeams' : IDL.Nat,
  'email' : IDL.Text,
  'totalPoints' : IDL.Nat,
  'picks' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat)),
});
export const Team = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Variant({ 'active' : IDL.Null, 'eliminated' : IDL.Null }),
  'name' : IDL.Text,
  'seed' : IDL.Nat,
  'points' : IDL.Nat,
});
export const TournamentPhase = IDL.Variant({
  'registration' : IDL.Null,
  'complete' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'addTeam' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Nat], []),
  'confirmPayment' : IDL.Func([IDL.Nat], [], []),
  'deleteEntry' : IDL.Func([IDL.Nat], [], []),
  'fetchAndSyncScores' : IDL.Func([], [IDL.Text], []),
  'getEntry' : IDL.Func([IDL.Nat], [Entry], ['query']),
  'getLeaderboard' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, Entry))],
      ['query'],
    ),
  'getTeams' : IDL.Func([], [IDL.Vec(Team)], ['query']),
  'registerEntry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat))],
      [IDL.Nat],
      [],
    ),
  'seedTeamsFromBracket' : IDL.Func([], [IDL.Nat], []),
  'seedTestData2025' : IDL.Func([], [IDL.Text], []),
  'setTournamentPhase' : IDL.Func([TournamentPhase], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'unconfirmPayment' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Entry = IDL.Record({
    'paymentConfirmed' : IDL.Bool,
    'participantName' : IDL.Text,
    'activeTeams' : IDL.Nat,
    'email' : IDL.Text,
    'totalPoints' : IDL.Nat,
    'picks' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat)),
  });
  const Team = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Variant({ 'active' : IDL.Null, 'eliminated' : IDL.Null }),
    'name' : IDL.Text,
    'seed' : IDL.Nat,
    'points' : IDL.Nat,
  });
  const TournamentPhase = IDL.Variant({
    'registration' : IDL.Null,
    'complete' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'addTeam' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Nat], []),
    'confirmPayment' : IDL.Func([IDL.Nat], [], []),
    'deleteEntry' : IDL.Func([IDL.Nat], [], []),
    'fetchAndSyncScores' : IDL.Func([], [IDL.Text], []),
    'getEntry' : IDL.Func([IDL.Nat], [Entry], ['query']),
    'getLeaderboard' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, Entry))],
        ['query'],
      ),
    'getTeams' : IDL.Func([], [IDL.Vec(Team)], ['query']),
    'registerEntry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat))],
        [IDL.Nat],
        [],
      ),
    'seedTeamsFromBracket' : IDL.Func([], [IDL.Nat], []),
    'seedTestData2025' : IDL.Func([], [IDL.Text], []),
    'setTournamentPhase' : IDL.Func([TournamentPhase], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'unconfirmPayment' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };