/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Entry {
  'participantName' : string,
  'activeTeams' : bigint,
  'totalPoints' : bigint,
  'picks' : Array<[bigint, bigint]>,
}
export type TournamentPhase = { 'registration' : null } |
  { 'complete' : null } |
  { 'inProgress' : null };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'addTeam' : ActorMethod<[string, bigint], bigint>,
  'fetchAndSyncScores' : ActorMethod<[], string>,
  'getEntry' : ActorMethod<[bigint], Entry>,
  'getLeaderboard' : ActorMethod<[], Array<[bigint, Entry]>>,
  'registerEntry' : ActorMethod<[string, Array<[bigint, bigint]>], bigint>,
  'seedTeamsFromBracket' : ActorMethod<[], bigint>,
  'setTournamentPhase' : ActorMethod<[TournamentPhase], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];