/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface Entry {
    paymentConfirmed: boolean;
    participantName: string;
    activeTeams: bigint;
    email: string;
    totalPoints: bigint;
    picks: Array<[bigint, bigint]>;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface http_header {
    value: string;
    name: string;
}
export interface Team {
    id: bigint;
    status: Variant_active_eliminated;
    name: string;
    seed: bigint;
    points: bigint;
}
export enum TournamentPhase {
    registration = "registration",
    complete = "complete",
    inProgress = "inProgress"
}
export enum Variant_active_eliminated {
    active = "active",
    eliminated = "eliminated"
}
export interface backendInterface {
    addTeam(name: string, seed: bigint): Promise<bigint>;
    batchUpdateTeamScores(updates: Array<[string, bigint, boolean]>): Promise<void>;
    confirmPayment(entryId: bigint): Promise<void>;
    deleteEntry(entryId: bigint): Promise<void>;
    fetchAndSyncScores(date: string): Promise<string>;
    getEntry(entryId: bigint): Promise<Entry>;
    getLeaderboard(): Promise<Array<[bigint, Entry]>>;
    getTeams(): Promise<Array<Team>>;
    registerEntry(participantName: string, email: string, picks: Array<[bigint, bigint]>): Promise<bigint>;
    resetTeamScores(): Promise<void>;
    seedTeamsFromBracket(): Promise<bigint>;
    setTournamentPhase(phase: TournamentPhase): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    unconfirmPayment(entryId: bigint): Promise<void>;
}
import type { Team as _Team, TournamentPhase as _TournamentPhase } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addTeam(arg0: string, arg1: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addTeam(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTeam(arg0, arg1);
            return result;
        }
    }
    async batchUpdateTeamScores(arg0: Array<[string, bigint, boolean]>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.batchUpdateTeamScores(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.batchUpdateTeamScores(arg0);
            return result;
        }
    }
    async confirmPayment(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.confirmPayment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.confirmPayment(arg0);
            return result;
        }
    }
    async deleteEntry(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEntry(arg0);
            return result;
        }
    }
    async fetchAndSyncScores(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchAndSyncScores(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchAndSyncScores(arg0);
            return result;
        }
    }
    async getEntry(arg0: bigint): Promise<Entry> {
        if (this.processError) {
            try {
                const result = await this.actor.getEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEntry(arg0);
            return result;
        }
    }
    async getLeaderboard(): Promise<Array<[bigint, Entry]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaderboard();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaderboard();
            return result;
        }
    }
    async getTeams(): Promise<Array<Team>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeams();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeams();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerEntry(arg0: string, arg1: string, arg2: Array<[bigint, bigint]>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.registerEntry(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerEntry(arg0, arg1, arg2);
            return result;
        }
    }
    async resetTeamScores(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetTeamScores();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetTeamScores();
            return result;
        }
    }
    async seedTeamsFromBracket(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.seedTeamsFromBracket();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedTeamsFromBracket();
            return result;
        }
    }
    async setTournamentPhase(arg0: TournamentPhase): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setTournamentPhase(to_candid_TournamentPhase_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setTournamentPhase(to_candid_TournamentPhase_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async unconfirmPayment(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unconfirmPayment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unconfirmPayment(arg0);
            return result;
        }
    }
}
function from_candid_Team_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Team): Team {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: {
        active: null;
    } | {
        eliminated: null;
    };
    name: string;
    seed: bigint;
    points: bigint;
}): {
    id: bigint;
    status: Variant_active_eliminated;
    name: string;
    seed: bigint;
    points: bigint;
} {
    return {
        id: value.id,
        status: from_candid_variant_n4(_uploadFile, _downloadFile, value.status),
        name: value.name,
        seed: value.seed,
        points: value.points
    };
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    eliminated: null;
}): Variant_active_eliminated {
    return "active" in value ? Variant_active_eliminated.active : "eliminated" in value ? Variant_active_eliminated.eliminated : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Team>): Array<Team> {
    return value.map((x)=>from_candid_Team_n2(_uploadFile, _downloadFile, x));
}
function to_candid_TournamentPhase_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TournamentPhase): _TournamentPhase {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TournamentPhase): {
    registration: null;
} | {
    complete: null;
} | {
    inProgress: null;
} {
    return value == TournamentPhase.registration ? {
        registration: null
    } : value == TournamentPhase.complete ? {
        complete: null
    } : value == TournamentPhase.inProgress ? {
        inProgress: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
